# Generated by Django 4.2.24 on 2025-09-04 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pretixbase", "0285_alter_customer_locale_alter_user_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReferencedCashfreeObject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                (
                    "reference",
                    models.CharField(db_index=True, max_length=190, unique=True),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pretixbase.order",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pretixbase.orderpayment",
                    ),
                ),
            ],
        ),
    ]
