# Generated by Django 4.2.24 on 2025-09-04 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pretix_cashfree", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="referencedcashfreeobject",
            name="order",
        ),
    ]
