name: Publish Python package

on:
  push:
    branches: [ main, master ]

permissions:
  contents: read

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    name: Publish
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v1
        with:
          python-version: 3.11
      
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.py') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      - name: Install build dependencies
        run: |
          sudo apt update && sudo apt install gettext
          python -m pip install --upgrade pip build twine
          pip install build twine
      
      - name: Build package
        run: python -m build

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          twine upload dist/* 